moses:
  namespace: ""
  tenantId: ""
  executionId: ""
  chartId: ""
  appSlug: ""

services:
  - name: app
    image:
      repository: "fullstack-unified-app"
      tag: "latest"
      pullPolicy: IfNotPresent
    port: 8080
    replicas: 1
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    healthCheck:
      enabled: true
      path: /health
    ingress: true

globalEnv:
  BASE_URL: ""
