{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-deployed-app.fullname" . }}-db-secret
  labels:
    {{- include "agent-deployed-app.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
